# Generated by Django 2.1.2 on 2018-11-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashcan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
