# Generated by Django 2.1.2 on 2018-11-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trashcan', '0002_trashcan_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('distance', models.FloatField(help_text='Distancia del cesor a la basura cm')),
                ('trash_can', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='trashcan.TrashCan')),
            ],
            options={
                'db_table': 'level',
            },
        ),
    ]
