# Generated by Django 2.1.2 on 2018-11-07 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trashcan', '0003_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(choices=[(0, 'Por Recoger'), (1, 'Trabajo Hecho')], default=0, max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('trash_can', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trashcan.TrashCan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'harvest',
            },
        ),
        migrations.AddField(
            model_name='trashcan',
            name='recicle',
            field=models.ManyToManyField(through='trashcan.Harvest', to=settings.AUTH_USER_MODEL),
        ),
    ]
