# Generated by Django 2.1.2 on 2018-11-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashcan', '0004_auto_20181107_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashcan',
            old_name='recicle',
            new_name='recyclers',
        ),
        migrations.AlterModelTable(
            name='harvest',
            table=None,
        ),
    ]
