# Generated by Django 2.1.2 on 2018-11-12 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trashcan', '0005_auto_20181112_0307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='harvest',
            unique_together={('user', 'trash_can', 'date')},
        ),
        migrations.AlterModelTable(
            name='harvest',
            table='harvest',
        ),
    ]
